FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential git libssl-dev zlib1g-dev \
    libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev \
    libgdbm-dev libdb5.3-dev libbz2-dev expat libexpat1-dev liblzma-dev libffi-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src

COPY cinder-meta-3.14 . 
WORKDIR /usr/src/cinder

RUN ./configure --enable-optimizations
RUN make -j$(nproc)
RUN make altinstall

RUN ln -s /usr/local/bin/python3.14 /usr/local/bin/python
RUN ln -s /usr/local/bin/pip3.14 /usr/local/bin/pip

WORKDIR /app
RUN rm -rf /usr/src/cinder

CMD ["python", "-c", "import sys; print('\\n[+] Cinder Base Image Ready! Version:', sys.version)"]